# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: make application.yml
      run: |
        # create application.yml
        cd ./src/main
        mkdir resources
        cd ./resources

        # application.yml 파일 생성하기
        touch ./application.yml

        # Secrets에 저장한 값을 application.yml 파일에 쓰기
        echo "${{ secrets.YML }}" >> ./application.yml

      shell: bash

    - name: Build with Gradle
      run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          
  ## 도커 이미지 빌드 후 도커허브에 push하기
    - name: web docker build and push
      run: |
        docker login -u ${{ secrets.hig26827463 }} -p ${{ secrets.!ig26827463 }}
        docker build -t ${{ secrets.hig26827463/travelmate }} .
        docker push ${{ secrets.hig26827463/travelmate }}

  ## 서버에 접속하여 도커 이미지를 pull 받고 실행하기
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          sudo docker image rm ${{ secrets.hig26827463/travelmate }}
          sudo docker pull ${{ secrets.hig26827463/travelmate }}
          sudo docker run -d -p 8080:8080 ${{ secrets.hig26827463/travelmate }}
